"""REQ-4014: Add sort_order to DataClassValue

Revision ID: 65a1e71fc006
Revises: da53f00e5892
Create Date: 2026-08-19 15:41:43.466396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65a1e71fc006'
down_revision: Union[str, None] = 'da53f00e5892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataclass_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataclass_values', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
